name: TF AKS DRIFT CHECK 12-2025

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_STORAGE_ACCOUNT_NAME: "itsajtfstatestorage"
  TF_CONTAINER_NAME: "tfstate"
  TF_STATE_KEY: "dev.tfstate"
  TF_STATE_RESOURCE_GROUP: "terraform-state-rg"
  

jobs:
  drift-check:
    name: Terraform Drift Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # - name: Login to Azure
      #   uses: azure/login@v1

      - name: Terraform Init (remote backend)
        run: |
          terraform -chdir=TF init \
            -backend-config="resource_group_name=${TF_STATE_RESOURCE_GROUP}" \
            -backend-config="storage_account_name=${TF_STORAGE_ACCOUNT_NAME}" \
            -backend-config="container_name=${TF_CONTAINER_NAME}" \
            -backend-config="key=${TF_STATE_KEY}"

      - name: Terraform Validate
        run: terraform -chdir=TF validate

      - name: Terraform Drift Check
        id: plan
        run: |
          set +e
          terraform -chdir=TF plan -var-file=dev.tfvars -detailed-exitcode
          echo "exitcode=$?" >> $GITHUB_OUTPUT

      - name: Interpret Drift Result
        run: |
          if [ "${{ steps.plan.outputs.exitcode }}" = "0" ]; then
            echo "✅ No drift detected"
            exit 0
          elif [ "${{ steps.plan.outputs.exitcode }}" = "2" ]; then
            echo "❌ DRIFT DETECTED between state and real infrastructure"
            exit 1
          else
            echo "❌ Terraform error"
            exit 1
          fi

