# f-backend-state-unlock-12-2025.yml
name: TF STATE UNLOCK (EMERGENCY)

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: "Terraform state lock ID"
        required: true

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  # uzywane przy RABC z modułu TF 
  TF_VAR_aks_ci_sp_object_id: ${{ secrets.AZURE_CLIENT_OBIECT_ID }}

  TF_STORAGE_ACCOUNT_NAME: "itsajtfstatestorage"
  TF_CONTAINER_NAME: "tfstate"
  TF_STATE_RESOURCE_GROUP: "terraform-state-rg"

jobs:
  unlock:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Validate confirmation
        run: |
          if [ "${{ inputs.confirm_destroy }}" != "DESTROY" ]; then
            echo "❌ Destroy not confirmed. Type DESTROY to proceed."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init (remote backend)
        run: |
          terraform -chdir=TF init \
            -backend-config="resource_group_name=${TF_STATE_RESOURCE_GROUP}" \
            -backend-config="storage_account_name=${TF_STORAGE_ACCOUNT_NAME}" \
            -backend-config="container_name=${TF_CONTAINER_NAME}" \
            -backend-config="key=${{ inputs.environment }}.tfstate"

      - name: Force unlock state
        run: |
          echo "yes" | terraform -chdir=TF force-unlock "${{ github.event.inputs.lock_id }}"





  
